import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import Footer from "./components/Footer";
import ChatInterface from "./components/ChatPopupBtn";
import { Toaster } from "sonner";
import { AppProvider } from "@/context/AppContext";
import { AuthPopup } from "@/components/AuthPopup";
import { CartPopup } from "@/components/CartPopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Luxury Gems - Fine Jewelry Collection",
  description: "Generated by create next app",
  icons: {
    icon: '/sparkles-favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased from-white via-orange-50/30 to-amber-50/40`}
      >
        <AppProvider>
          <Navbar />
          {children}
          <Footer />
          {/* <ChatInterface /> */}
          <Toaster position="top-right" richColors />

          {/* Popups */}
          <AuthPopup />
          <CartPopup />
        </AppProvider>
      </body>
    </html>
  );
}
